---
- hosts: all
  become: yes
  vars:
    user: "ubuntu"
    home: "/home/{{user}}"
  tasks:
  - name: setup hosts
    copy: src=hosts dest=/etc/hosts

  - name: update repos
    apt: update_cache=true

  - name: install git
    apt: pkg=git state=installed

  - name: install java
    apt: pkg=openjdk-8-jdk state=installed

  - name: install maven
    apt: pkg=maven state=installed

  - name: copy keystore
    copy: src=keystore dest={{home}}/.keystore owner={{user}} group={{user}}

  - name: clone repo
    git: repo=https://github.com/Camiloasc1/SoftwareArchitectureUNAL.git dest={{home}}/SoftwareArchitectureUNAL force=yes accept_hostkey=yes

  - name: chown
    file: path={{home}}/SoftwareArchitectureUNAL owner={{user}} group={{user}} state=directory recurse=yes
