---
- hosts: database
  become: yes
  vars:
    mysql_root_pass: architecture
  tasks:
  - name: update repos
    apt: update_cache=true

  - name: MySQL root password
    debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_pass | quote}}' vtype='password'

  - name: MySQL root password again
    debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_pass | quote}}' vtype='password'

  - name: install mysql
    apt: pkg=mysql-server state=installed

  - name: install git
    apt: pkg=git state=installed

  - name: clone repo
    git: repo=https://github.com/Camiloasc1/SoftwareArchitectureUNAL.git dest=SoftwareArchitectureUNAL accept_hostkey=true

  - name: setup user and database
    command: ./db.sh chdir=SoftwareArchitectureUNAL/ansible creates=/var/lib/mysql/tomee

  - name: setup MySQL
    copy: src=my.cfg dest=/etc/mysql/my.cfg

  - name: start and enable MySQL
    service: name=mysql state=started enabled=yes
