---
- hosts: nodes
  become: yes
  tasks:
  - name: clone repo
    git: repo=https://github.com/Camiloasc1/SoftwareArchitectureUNAL.git dest=SoftwareArchitectureUNAL force=yes accept_hostkey=yes

  - name: chown
    file: path=SoftwareArchitectureUNAL owner=architecture group=architecture state=directory recurse=yes

  - name: TomEE cluster node ip
    template: src=server.j2 dest=SoftwareArchitectureUNAL/src/main/tomee/conf/server.xml owner=architecture group=architecture

  - name: multicast route
    script: nodeRoute.sh
