---
- hosts: database
  become: yes
  vars:
    ldap_root_pass: architecture
  tasks:
  - name: update repos
    apt: update_cache=true

  - name: LDAP root password
    debconf: name='slapd' question='slapd/password1' value='{{ldap_root_pass | quote}}' vtype='password'

  - name: LDAP root password again
    debconf: name='slapd' question='slapd/password2' value='{{ldap_root_pass | quote}}' vtype='password'

  - name: install LDAP server
    apt: pkg=slapd state=installed

  - name: install LDAP Utils
    apt: pkg=ldap-utils state=installed

  - name: start and enable LDAP
    service: name=slapd state=started enabled=yes

  - name: install git
    apt: pkg=git state=installed

  - name: clone repo
    git: repo=https://github.com/Camiloasc1/SoftwareArchitectureUNAL.git dest=SoftwareArchitectureUNAL accept_hostkey=true

  - name: populate LDAP
    command: ldapmodify -Y EXTERNAL -H ldapi:/// -f ldap.ldif chdir=SoftwareArchitectureUNAL/ansible
