---
- hosts: nodes
  become: yes
  tasks:
  - name: setup repos
    copy: src=sources.list dest=/etc/apt/sources.list

  - name: update repos
    apt: update_cache=true

  - name: install git
    apt: pkg=git state=installed

  - name: install java
    apt: pkg=openjdk-8-jdk state=installed

  - name: install maven
    apt: pkg=maven state=installed

  - name: clone repo
    git: repo=https://github.com/Camiloasc1/SoftwareArchitectureUNAL.git dest=SoftwareArchitectureUNAL accept_hostkey=true

  - name: run
    command: ./run.sh & chdir=SoftwareArchitectureUNAL
