
package unal.architecture.credits;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MakeAcquiredProductWS", targetNamespace = "http://Service.BusinessLogic/", wsdlLocation = "http://192.168.2.166:8080/Kwinty/MakeAcquiredProductWS?wsdl")
public class MakeAcquiredProductWS_Service
    extends Service
{

    private final static URL MAKEACQUIREDPRODUCTWS_WSDL_LOCATION;
    private final static WebServiceException MAKEACQUIREDPRODUCTWS_EXCEPTION;
    private final static QName MAKEACQUIREDPRODUCTWS_QNAME = new QName("http://Service.BusinessLogic/", "MakeAcquiredProductWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.2.166:8080/Kwinty/MakeAcquiredProductWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAKEACQUIREDPRODUCTWS_WSDL_LOCATION = url;
        MAKEACQUIREDPRODUCTWS_EXCEPTION = e;
    }

    public MakeAcquiredProductWS_Service() {
        super(__getWsdlLocation(), MAKEACQUIREDPRODUCTWS_QNAME);
    }

    public MakeAcquiredProductWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAKEACQUIREDPRODUCTWS_QNAME, features);
    }

    public MakeAcquiredProductWS_Service(URL wsdlLocation) {
        super(wsdlLocation, MAKEACQUIREDPRODUCTWS_QNAME);
    }

    public MakeAcquiredProductWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAKEACQUIREDPRODUCTWS_QNAME, features);
    }

    public MakeAcquiredProductWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MakeAcquiredProductWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MakeAcquiredProductWS
     */
    @WebEndpoint(name = "MakeAcquiredProductWSPort")
    public MakeAcquiredProductWS getMakeAcquiredProductWSPort() {
        return super.getPort(new QName("http://Service.BusinessLogic/", "MakeAcquiredProductWSPort"), MakeAcquiredProductWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MakeAcquiredProductWS
     */
    @WebEndpoint(name = "MakeAcquiredProductWSPort")
    public MakeAcquiredProductWS getMakeAcquiredProductWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Service.BusinessLogic/", "MakeAcquiredProductWSPort"), MakeAcquiredProductWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAKEACQUIREDPRODUCTWS_EXCEPTION!= null) {
            throw MAKEACQUIREDPRODUCTWS_EXCEPTION;
        }
        return MAKEACQUIREDPRODUCTWS_WSDL_LOCATION;
    }

}
